# Generated by Django 5.0.6 on 2025-03-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPOCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=50)),
                ('issue_price', models.FloatField()),
                ('lot_size', models.IntegerField()),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
            ],
        ),
    ]
