# Generated by Django 5.0.6 on 2025-03-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipocompany',
            name='drhp_pdf',
            field=models.FileField(blank=True, null=True, upload_to='ipo_pdfs/'),
        ),
        migrations.AddField(
            model_name='ipocompany',
            name='issue_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ipocompany',
            name='issue_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ipocompany',
            name='listing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipocompany',
            name='listing_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipocompany',
            name='market_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipocompany',
            name='price_band_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipocompany',
            name='price_band_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipocompany',
            name='rhp_pdf',
            field=models.FileField(blank=True, null=True, upload_to='ipo_pdfs/'),
        ),
        migrations.AlterField(
            model_name='ipocompany',
            name='symbol',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
